CREATE TABLE full_insurance_data.Current_Conditions AS
SELECT 
  HHX AS ID,
  row_number() over (order by HHX) as Health_Condition_ID,
  PHSTAT_A AS Gen_Health,
  HYPDIF_A AS Hypertension_Visit,
  HYP12M_A AS Hypertension12M,
  HYPMED_A AS Hypertension_med,
  CHL12M_A AS Cholesterol12M,
  CHLMED_A AS Cholesterol_med,
  ASTILL_A AS Asthma,
  ASAT12M_A AS Asthma_episode,
  ASER12M_A AS Asthma_ERVisit,
  GESDIB_A AS Gestational_Diabetes,
  DIFYRSTC1_A AS Age_Diabetes,
  DIBPILL_A AS Diabetic_pill,
  DIBINS_A AS Insulin,
  DIBINSTIME_A AS Insulin_Time,
  DIBTYPE_A AS Diabetes_Type,
  CFSNOW_A AS Chronic_Fatigue_Syndrome, 
  MEDRXTRT_A AS Med_WeakImmune,
  HLTHCOND_A AS Health_WeakImmune,
  EPIMED_A AS Epilepsy_med,
  EPINUMSEZP_A AS Seizure12M,
  EPIDR_A AS Epilepsy_Dr,
  PREGNOW_A AS Pregnant,
  HEIGHTTC_A AS Height,
  WEIGHTLBTC_A AS Weight
FROM `chrome-backbone-393801.full_insurance_data.full_data`;

CREATE TABLE full_insurance_data.Health_History AS
SELECT 
  HHX AS ID,
  row_number() over (order by HHX)+27651 as Health_Condition_ID,
  CVDDIAG_A,
  POSTEST_A,
  LONGCVD_A,
  BLADDCAN_A,
  BLADDAGETC_A,
  BLOODCAN_A,
  BLOODAGETC_A,
  BONECAN_A,
  BONEAGETC_A,
  BRAINCAN_A,
  BRAINAGETC_A,
  BREASCAN_A,
  BREASAGETC_A,
  CERVICAN_A,
  CERVIAGETC_A,
  COLONCAN_A,
  COLONAGETC_A,
  ESOPHCAN_A,
  ESOPHAGETC_A,
  GALLBCAN_A,
  GALLBAGETC_A,
  LARYNCAN_A,
  LARYNAGETC_A,
  LEUKECAN_A,
  LEUKEAGETC_A,
  LIVERCAN_A,
  LIVERAGETC_A,
  LUNGCAN_A,
  LUNGAGETC_A,
  LYMPHCAN_A,
  LYMPHAGETC_A,
  MELANCAN_A,
  MELANAGETC_A,
  MOUTHCAN_A,
  MOUTHAGETC_A,
  OVARYCAN_A,
  OVARYAGETC_A,
  PANCRCAN_A,
  PANCRAGETC_A,
  PROSTCAN_A,
  PROSTAGETC_A,
  RECTUCAN_A,
  RECTUAGETC_A,
  SKNMCAN_A,
  SKNMAGETC_A,
  SKNNMCAN_A,
  SKNNMAGETC_A,
  SKNDKCAN_A,
  SKNDKAGETC_A,
  STOMACAN_A,
  STOMAAGETC_A,
  THROACAN_A,
  THROAAGETC_A,
  THYROCAN_A,
  THYROAGETC_A,
  UTERUCAN_A,
  UTERUAGETC_A,
  HDNCKCAN_A,
  HDNCKAGETC_A,
  COLRCCAN_A,
  COLRCAGETC_A,
  OTHERCANP_A,
  OTHERAGETC_A
FROM `chrome-backbone-393801.full_insurance_data.full_data`;

CREATE TABLE full_insurance_data.Health_Problem AS
SELECT 
  HHX AS ID,
  row_number() over (order by HHX)+55302 as Health_Condition_ID,
  HYPEV_A AS Hypertension,
  CHLEV_A AS High_Cholesterol,
  CHDEV_A AS CoronaryHeartDisease,
  ANGEV_A AS Angina,
  MIEV_A AS HeartAttack,
  STREV_A AS Stroke,
  ASEV_A AS Asthma,
  CANEV_A AS Cancer,
  BLADDCAN_A,
  BLADDAGETC_A,
  BLOODCAN_A,
  BLOODAGETC_A,
  BONECAN_A,
  BONEAGETC_A,
  BRAINCAN_A,
  BRAINAGETC_A,
  BREASCAN_A,
  BREASAGETC_A,
  CERVICAN_A,
  CERVIAGETC_A,
  COLONCAN_A,
  COLONAGETC_A,
  ESOPHCAN_A,
  ESOPHAGETC_A,
  GALLBCAN_A,
  GALLBAGETC_A,
  LARYNCAN_A,
  LARYNAGETC_A,
  LEUKECAN_A,
  LEUKEAGETC_A,
  LIVERCAN_A,
  LIVERAGETC_A,
  LUNGCAN_A,
  LUNGAGETC_A,
  LYMPHCAN_A,
  LYMPHAGETC_A,
  MELANCAN_A,
  MELANAGETC_A,
  MOUTHCAN_A,
  MOUTHAGETC_A,
  OVARYCAN_A,
  OVARYAGETC_A,
  PANCRCAN_A,
  PANCRAGETC_A,
  PROSTCAN_A,
  PROSTAGETC_A,
  RECTUCAN_A,
  RECTUAGETC_A,
  SKNMCAN_A,
  SKNMAGETC_A,
  SKNNMCAN_A,
  SKNNMAGETC_A,
  SKNDKCAN_A,
  SKNDKAGETC_A,
  STOMACAN_A,
  STOMAAGETC_A,
  THROACAN_A,
  THROAAGETC_A,
  THYROCAN_A,
  THYROAGETC_A,
  UTERUCAN_A,
  UTERUAGETC_A,
  HDNCKCAN_A,
  HDNCKAGETC_A,
  COLRCCAN_A,
  COLRCAGETC_A,
  OTHERCANP_A,
  OTHERAGETC_A,
  NUMCAN_A,
  PREDIB_A AS Prediabetes,
  DIBEV_A AS GestationalDiabetes,
  DIBAGETC_A,
  COPDEV_A AS COPD,
  ARTHEV_A AS Arthritis,
  DEMENEV_A AS Dementia,
  ANXEV_A AS Anxiety_Disorder,
  DEPEV_A AS Depression,
  CFSEV_A,
  EPIEV_A AS Epilepsy,
  ANXFREQ_A,
  ANXMED_A,
  ANXLEVEL_A,
  DEPFREQ_A,
  DEPMED_A,
  DEPLEVEL_A,
  PHQCAT_A AS Depression_Severity,
  GADCAT_A AS Anxiety_Severity,
  FGELEVTRD_A AS Fatigue
FROM `chrome-backbone-393801.full_insurance_data.full_data`;

CREATE TABLE full_insurance_data.Vaccination AS
SELECT 
  HHX AS ID,
  row_number() over (order by HHX)+82953 as Health_Condition_ID,
  SHTFLU12M_A AS FLUVAC_12M,
  SHTFLUM_A AS FLUVAC_M,
  SHTFLUY_A AS FLUVAC_Y,
  FLUPREG_A AS FLUVAC_Preg,
  FLUPREG2_A AS FLUVAC_Preg2,
  SHTCVD191_A AS COVIDVAC,
  SHTCVD19NM_A AS COVIDVAC_Num,
  CVDVAC1M_A AS COVIDVAC_M,
  CVDVAC1Y_A AS COVIDVAC_Y,
  CVDVAC2M_A AS COVIDVAC_M2,
  CVDVAC2Y_A AS COVIDVAC_Y2,
  SHOTTYPER_A AS COVIDVAC_Brand,
  SHOTTYPE_A AS COVIDVAC_Brand2,
  SHOTTYPE1_A AS COVIDVAC_Brand3,
  SHTPNUEV_A AS PneunomiaVAC,
  SHTPNEUNB_A AS PneumoniaVAC_Num,
  SHTSHINGL1_A AS ShinglesVAC,
  SHINGYEARP_A AS ShinglesVAC_Y,
  SHINGWHEN1_A AS ShinglesVAC_LastShot, 
  SHINGRIX2_A AS ShingrixVAC,
  SHINGRIXN2_A AS ShingrixVAC_Num,
  SHINGRIXFS_A AS ShingrixVAC_FS,
  TDAPPREG_A AS TdapVAC,
  SHTTETANUS_A AS TetanusVAC,
  SHTTDAP_A AS TetanusVAC_Type,
  SHTHPV_A AS HPVVAC,
  SHTHPVAGE_A AS HPVVAC_Age
FROM `chrome-backbone-393801.full_insurance_data.full_data`;

CREATE TABLE full_insurance_data.Therapy_Counseling AS
SELECT 
  HHX AS ID,
  row_number() over (order by HHX)+110604 as Health_Condition_ID,
  EYEEX12M_A AS EyeExam12M,
  THERA12M_A AS PT_Therapy12M,
  HOMEHC12M_A AS HomeCare12M,
  MHTHRPY_A AS MentalHealth_Therapy12m,
  MHTPYNOW_A AS  MentalHealth_TherapyNow,
  CHIROPAIN_A AS Chiropractor,
  ACUPAIN_A AS Acupuncture,
  MASS_A AS Massage,
  MASSPAIN_A AS Massage_pain,
  NATUR_A AS Naturopathy,
  NATURPAIN_A AS Naturopathy_pain,
  ARTTHPY_A AS Therapist,
  MUSICTHPY_A AS Music_therapist,
  MEDITATE_A AS Meditation
FROM `chrome-backbone-393801.full_insurance_data.full_data`;

CREATE TABLE full_insurance_data.Disability AS
SELECT 
  HHX AS ID,
  row_number() over (order by HHX)+138255 as Health_Condition_ID,
  DISAB3_A AS Disability
FROM `chrome-backbone-393801.full_insurance_data.full_data`;


Create table `full_insurance_data.Health_Condition`
AS
Select * FROM (
SELECT ID, Health_Condition_ID FROM `full_insurance_data.Current_Conditions`
UNION ALL
SELECT ID, Health_Condition_ID FROM `full_insurance_data.Health_History`
UNION ALL
SELECT ID, Health_Condition_ID FROM `full_insurance_data.Health_Problem`
UNION ALL
SELECT ID, Health_Condition_ID FROM `full_insurance_data.Vaccination`
UNION ALL
SELECT ID, Health_Condition_ID FROM `full_insurance_data.Therapy_Counseling`
UNION ALL 
SELECT ID, Health_Condition_ID FROM `full_insurance_data.Disability`
) as n;
